sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull drachtio/drachtio-server:latest
  - docker pull drachtio/sipp:latest
  - docker pull drachtio/drachtio-freeswitch-mrf:latest
  - docker images

script:
  - npm test
